base_url = "https://jake-shadle.github.io"

title = "Jake's Blog"
default_language = "en"

theme = "Zulma"
paginate_by = 5

taxonomies = [
    { name = "tags", paginate_by = 5 },
    { name = "categories", paginate_by = 5 },
]

[markdown]
highlight_theme = "OneHalfDark"
highlight_code = true
render_emoji = true

[extra]
zulma_title = "Jake's Blog"
zulma_brand = { text = "Home" }
zulma_theme = "slate"
zulma_menu = [
    { url = "$BASE_URL/categories", name = "Categories" },
    { url = "$BASE_URL/tags", name = "Tags" },
    { url = "https://github.com/Jake-Shadle", name = "Github" },
    { url = "https://twitter.com/Ca1ne", name = "Twitter" },
]
