# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://Jake-Shadle.github.io"

# Site title
title = "Jake's Blog"

# Copyright
copyright = "(c) 2016 Jake Shadle."

# Language
languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "jake-blog"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Jake Shadle"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "Jake's Blog"
    topline = "words about stuff"
    footline = "code with <i class='fa fa-heart'></i> and probably <i class='fa fa-frown-o'></i>"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "monokai_sublime"

    # Google Analytics.
    googleAnalytics = "UA-84938518-1"

    # Sidebar social links.
    github = "Jake-Shadle" # Your Github profile ID
    twitter = "Ca1ne" # Your Twitter profile ID

    # Sidebar RSS link: will only show up if there is a RSS feed
    # associated with the current page
    rss = true

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

